# note setting yarnPath as yarn 3 is provided by nix shell
nodeLinker: pnp

packageExtensions:
  "@trufflesuite/eth-json-rpc-filters@*":
    # Used in module code while only declared in dev deps
    dependencies:
      pify: ^3.0.0

npmPublishAccess: public

npmScopes:
  rhino.fi:
    npmAlwaysAuth: false
    npmAuthToken: ${NPM_ACCESS_TOKEN-}
    npmPublishRegistry: https://registry.npmjs.org
